include ../config.mak

SRCS=	source/PlayBack_api.c\
			source/dec_api.c \
		 	source/disp_api.c \
	    source/prv_osd.c \
	    source/prv_err.c \
	    source/tw_tvp5158.c \
	    source/voa_vt.c \
	    source/h264_stream.c \
	    source/bs.c	\
	    source/h264_sei.c	


TARGET = Preview
INCLUDE += -I../drv/Include

include ../target.mak
