include ../config.mak


SRCS =	./source/GB_sipd.c \
		./source/GB_parser.c \
		./source/GB_adapter.c \
		./source/GB_Decode_PS_Data.c \
	  ./source/rtpdec.c \
	  ./source/mpeg.c \


TARGET = GB28181

INCLUDE +=	-I./Include -I./Include/mxml -I./Include/osip2 -I./Include/osipparser2 -I./Include/osipparser2/headers

include ../../target.mak